### ISSUE TITLE
[HELP] No module named 'yaml'

### ISSUE THREAD

**Issue by mzch** [TheReverend403/pste#7]
When I tried `flask assets build`, the following error occurred.

```python
(pste-Pb86S9Y9-py3.8) pste@lt:~/pste$ flask assets build
Usage: flask assets build [OPTIONS]

Error: While importing "pste", an ImportError was raised:

Traceback (most recent call last):
  File "/srv/pste/.cache/pypoetry/virtualenvs/pste-Pb86S9Y9-py3.8/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/srv/pste/pste/pste/__init__.py", line 20, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

Could anyone tell me how to fix this issue?

**Comment by mzch** [comment]
Fixed, but I had to `poetry add pyyaml`

**Comment by lwatsondev** [comment]
Thanks. You may need to run `git reset --hard HEAD` to pull the changes as you now have local changes from adding pyyaml yourself.
